### ISSUE TITLE
Add project license

### ISSUE THREAD

**Issue by mrksmrtn** [nilaysavant/yew-flow#1]
Could you please add a license for this project? I am considering using this for a project but the licensing would need to be clear. May I suggest the same license as Yew? It's dual licensed MIT/Apache (but maybe MIT is enough?). I'm happy to send a PR if that helps. Thanks!

**Comment by nilaysavant** [comment]
Sure. I'll add one!

**Comment by nilaysavant** [comment]
Added! https://github.com/nilaysavant/yew-flow/commit/9dd0625be59d0d23519f39af4b276a773731277c

**Comment by mrksmrtn** [comment]
That was quick! Thank you!
